library(data.table)

# Works with dataframes generated by env-download-functions.R

# Operate on one parameter by another (e.g. mean temp by wind speed)
apply_by <- function(data,
                         param = "Dew point temp",
                         by = "2min avg wind dir (deg)",
                         operation = mean,
                         by_colname = "By",
                         calc_colname = "Calc") {

    print(operation)
    df <- data[grepl("[0-9]", get(param)) & grepl("[0-9]", get(by)),
            .(operation(as.numeric(get(param)))),
            by = .(get("station"), as.numeric(get(by)))]

    colnames(df) <- c("station", by_colname, calc_colname)

    return(df)
}
